"use client";
import { useState } from "react";

const SUPABASE_URL = "https://acikiygkeqdylfrfjlua.supabase.co";
const SUPABASE_KEY = "sb_publishable_i3PbEymn-_QHCTezB85kbA_2NxBES_1";
const P=[{l:"Cafe offert",c:"#FF6B6B",e:"☕"},{l:"10% rabais",c:"#4ECDC4",e:"🎟"},{l:"Dessert gratuit",c:"#FFE66D",e:"🍰"},{l:"Boisson offerte",c:"#A8E6CF",e:"🥤"},{l:"15% rabais",c:"#FF8B94",e:"💸"},{l:"Entree gratuite",c:"#B4A7D6",e:"🎁"}];

async function saveLead(email, prize) {
  await fetch(SUPABASE_URL+"/rest/v1/leads", {method:"POST",headers:{"Content-Type":"application/json","apikey":SUPABASE_KEY,"Authorization":"Bearer "+SUPABASE_KEY},body:JSON.stringify({email,prize})});
}

export default function Home() {
  const[s,setS]=useState(false);const[r,setR]=useState(0);const[w,setW]=useState(null);const[m,setM]=useState(false);const[em,setEm]=useState("");const[st,setSt]=useState("play");
  const spin=()=>{if(s)return;setS(true);setM(false);const t=r+(5+Math.floor(Math.random()*5))*360+Math.floor(Math.random()*360);setR(t);setTimeout(()=>{setS(false);setW(P[Math.floor(((360-(t%360)+90)%360)/60)%6]);setSt("email");setM(true);},4000);};
  const claim=async()=>{if(!em)return;await saveLead(em,w?.l||"");setSt("win");};
  const seg=60,rad=140,cx=160,cy=160;
  const path=i=>{const a1=(i*seg-90)*Math.PI/180,a2=((i+1)*seg-90)*Math.PI/180;return"M "+cx+" "+cy+" L "+(cx+rad*Math.cos(a1))+" "+(cy+rad*Math.sin(a1))+" A "+rad+" "+rad+" 0 0 1 "+(cx+rad*Math.cos(a2))+" "+(cy+rad*Math.sin(a2))+" Z";};
  const tp=i=>{const a=((i+.5)*seg-90)*Math.PI/180;return{x:cx+rad*.62*Math.cos(a),y:cy+rad*.62*Math.sin(a),rot:(i+.5)*seg};};
  return(<div className="min-h-screen bg-gradient-to-br from-slate-900 via-purple-900 to-slate-900 flex flex-col items-center justify-center p-4"><h1 className="text-4xl font-bold text-white mb-2 text-center">🎡 Tourne et Gagne !</h1><p className="text-purple-200 mb-8 text-center">Tourne la roue pour gagner un prix</p><div className="relative mb-8"><div className="absolute -top-3 left-1/2 -translate-x-1/2 z-10 w-0 h-0" style={{borderLeft:"12px solid transparent",borderRight:"12px solid transparent",borderTop:"28px solid #FFE66D"}}/><div style={{transform:"rotate("+r+"deg)",transition:s?"transform 4s cubic-bezier(0.17,0.67,0.12,0.99)":"none"}}><svg width="320" height="320" viewBox="0 0 320 320">{P.map((p,i)=>(<g key={i}><path d={path(i)} fill={p.c} stroke="white" strokeWidth="2"/><text x={tp(i).x} y={tp(i).y} textAnchor="middle" dominantBaseline="middle" fontSize="22" transform={"rotate("+tp(i).rot+","+tp(i).x+","+tp(i).y+")"}>{p.e}</text></g>))}<circle cx={cx} cy={cy} r="22" fill="white" stroke="#6B46C1" strokeWidth="4"/><text x={cx} y={cy} textAnchor="middle" dominantBaseline="middle" fontSize="16">🎯</text></svg></div></div><button onClick={spin} disabled={s} className="px-10 py-4 bg-gradient-to-r from-purple-600 to-pink-500 text-white text-xl font-bold rounded-full shadow-lg hover:scale-105 transition-transform disabled:opacity-50">{s?"En train de tourner...":"🎰 Tourner la roue !"}</button>{m&&(<div className="fixed inset-0 bg-black/70 flex items-center justify-center z-50 p-4"><div className="bg-white rounded-3xl p-8 max-w-sm w-full text-center shadow-2xl">{st==="email"&&(<div><div className="text-6xl mb-4">{w&&w.e}</div><h2 className="text-2xl font-bold mb-2">Felicitations !</h2><p className="text-2xl font-bold mb-6" style={{color:w&&w.c}}>{w&&w.l}</p><input type="email" placeholder="ton@email.com" value={em} onChange={e=>setEm(e.target.value)} className="w-full border-2 border-purple-200 rounded-xl px-4 py-3 mb-4 text-center"/><button onClick={claim} className="w-full py-3 bg-gradient-to-r from-purple-600 to-pink-500 text-white font-bold rounded-xl">Reclamer mon prix 🎁</button></div>)}{st==="win"&&(<div><div className="text-6xl mb-4">⭐</div><h2 className="text-2xl font-bold mb-4">Derniere etape !</h2><p className="text-gray-600 mb-6">Laisse un avis Google pour ton <strong>{w&&w.l}</strong></p><a href="https://g.page/r/TON_LIEN" target="_blank" rel="noopener noreferrer" className="block w-full py-4 bg-blue-500 text-white font-bold rounded-xl mb-3">⭐ Laisser un avis Google</a><button onClick={()=>{setM(false);setSt("play");setEm("");}} className="text-gray-400 text-sm">Fermer</button></div>)}</div></div>)}<p className="text-purple-300 text-xs mt-8">FidUP Canada</p></div>);
}
